apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mydeploy1
  template:
    metadata:
      name: mypod1
      labels:
        name: mydeploy1
    spec:
      containers:
      - name: mycontainer
        image: nasirpatel/ci-pipeline:latest   # replace with your Docker-image pushed on Dockerhub
        ports:
        - containerPort: 8080
